# Generated by Django 4.1.5 on 2023-02-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio_Converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
