# Generated by Django 4.1.5 on 2023-02-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio_Converter', '0002_alter_link_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(blank=True, default='my_link', max_length=500, null=True),
        ),
    ]
